/*
MIT License

Copyright (c) 2019 Egor Nepomnyaschih

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

const fs = require('fs'),
	path = require('path'),
	CleanWebpackPlugin = require('clean-webpack-plugin'),
	cli = require('./cli'),
	{readdirDownwards} = require('./dir');

const supportedOptions = [
	["test-paths", "p", "Comma-separated paths of files/folders to include in the build", "."],
	["help", "h", "Show this help"]
];

const initOptions = () => {
	const script = "webpack.conf.js";
	const options = cli.parseCliArguments(process.argv.slice(process.argv.indexOf(script) + 1), supportedOptions);
	if (options.help) {
		cli.showCliHelp("webpack --config " + script, supportedOptions);
		process.exit(0);
	}
	return options;
};

try {
	const options = initOptions();
	const files = [];
	const dir = path.resolve(__dirname, "src");
	for (let entry of options.testPaths.split(",")) {
		for (let {id, stat} of readdirDownwards(path.resolve(dir, entry))) {
			if (stat.isFile() && id && !id.startsWith("_") && !id.endsWith(".d.ts") && path.extname(id) === ".ts") {
				files.push(entry + "/" + id);
			}
		}
	}
	fs.writeFileSync(path.resolve(dir, "all.js"),
		"// This file is auto-generated by `npm run build` or `npm run watch`. Don't edit it.\n\n"
		+ files.map(file => `import "./${file}";`).join(";\n"));
	module.exports = {
		context: __dirname,
		entry: {
			test: "./src/all.js"
		},
		output: {
			filename: 'bundle.js',
			path: path.resolve(__dirname, "dist"),
			publicPath: '/'
		},
		resolve: {
			extensions: [".ts", ".js"]
		},
		mode: 'development',
		devtool: 'inline-source-map',
		module: {
			rules: [
				{
					test: /\.ts$/,
					exclude: /node_modules/,
					loader: [
						{
							loader: 'babel-loader',
							query: {
								presets: [
									[
										"env",
										{
											"targets": {
												"browsers": [
													"last 2 versions",
													"IE >= 11"
												]
											}
										}
									]
								]
							}

						},
						{
							loader: "ts-loader"
						}
					]
				}
			]
		},
		plugins: [
			new CleanWebpackPlugin(["dist"], {
				root: __dirname
			})
		],
		stats: {
			assets: false,
			children: false,
			entrypoints: false,
			modules: false
		}
	};
} catch (e) {
	console.error(e);
	process.exit(1);
}
