# MIT License
#
# Copyright (c) 2019-2022 Egor Nepomnyaschih
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: ts-time
input: src
output: dist
docTitle: Modules

references:
  MS_PER_DAY:
    file: ts-time/constants
    symbol: MS_PER_DAY

  MS_PER_HOUR:
    file: ts-time/constants
    symbol: MS_PER_HOUR

  MIDNIGHT:
    file: ts-time/LocalTime
    symbol: MIDNIGHT

  MONDAY:
    file: ts-time/DayOfWeek
    symbol: MONDAY

  TUESDAY:
    file: ts-time/DayOfWeek
    symbol: TUESDAY

  SUNDAY:
    file: ts-time/DayOfWeek
    symbol: SUNDAY

  JANUARY:
    file: ts-time/Month
    symbol: JANUARY

  FEBRUARY:
    file: ts-time/Month
    symbol: FEBRUARY

  MARCH:
    file: ts-time/Month
    symbol: MARCH

  APRIL:
    file: ts-time/Month
    symbol: APRIL

  MAY:
    file: ts-time/Month
    symbol: MAY

  JUNE:
    file: ts-time/Month
    symbol: JUNE

  JULY:
    file: ts-time/Month
    symbol: JULY

  AUGUST:
    file: ts-time/Month
    symbol: AUGUST

  SEPTEMBER:
    file: ts-time/Month
    symbol: SEPTEMBER

  OCTOBER:
    file: ts-time/Month
    symbol: OCTOBER

  NOVEMBER:
    file: ts-time/Month
    symbol: NOVEMBER

  DECEMBER:
    file: ts-time/Month
    symbol: DECEMBER

  DAY_PERIOD:
    file: ts-time/Period
    symbol: DAY_PERIOD

  MONTH_PERIOD:
    file: ts-time/Period
    symbol: MONTH_PERIOD

  UTC:
    file: ts-time/Zone
    symbol: UTC

  LOCAL_ZONE_ID:
    file: ts-time/ZoneId
    symbol: LOCAL_ZONE_ID

  DAY_OF_MONTH_COMPILER:
    file: ts-time-format/DateFormatter
    symbol: DAY_OF_MONTH_COMPILER

  MONTH_COMPILER:
    file: ts-time-format/DateFormatter
    symbol: MONTH_COMPILER

  DEFAULT_TEMPORAL_CONTEXT:
    file: ts-time-format/constants
    symbol: DEFAULT_TEMPORAL_CONTEXT

  DATE_COMPILERS:
    file: ts-time-format/DateFormatter
    symbol: DATE_COMPILERS

  TIME_COMPILERS:
    file: ts-time-format/TimeFormatter
    symbol: TIME_COMPILERS

  DATE_TIME_COMPILERS:
    file: ts-time-format/DateTimeFormatter
    symbol: DATE_TIME_COMPILERS

  OFFSET_COMPILERS:
    file: ts-time-format/OffsetFormatter
    symbol: OFFSET_COMPILERS

  ZoneId:
    file: ts-time/Zone
    symbol: ZoneId

  ZoneOffset:
    file: ts-time/Zone
    symbol: ZoneOffset

  ofZone:
    file: ts-time/Zone
    symbol: ZoneId
    member: of
    static: true
    label: of

  Date:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

  DateTimeFormat:
    label: Intl.DateTimeFormat
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

  coreConstants:
    file: ts-time/constants
    label: constants

  formatConstants:
    file: ts-time-format/constants
    label: constants

  coreUtils:
    file: ts-time/utils
    label: utils

  formatUtils:
    file: ts-time-format/utils
    label: utils

  parsePattern:
    file: ts-time-format/utils
    symbol: parsePattern

  TemporalFormatComponent:
    file: ts-time-format/TemporalFormatter
    symbol: TemporalFormatComponent

  Error:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

  TemporalError:
    file: ts-time/errors
    symbol: TemporalError

  TemporalParsingError:
    file: ts-time/errors
    symbol: TemporalParsingError

  InvalidTemporalFormatError:
    file: ts-time/errors
    symbol: InvalidTemporalFormatError

  InvalidTimeZoneError:
    file: ts-time/errors
    symbol: InvalidTimeZoneError

  MismatchingOffsetError:
    file: ts-time/errors
    symbol: MismatchingOffsetError

  InvalidDayOfWeekError:
    file: ts-time/errors
    symbol: InvalidDayOfWeekError

  InvalidMonthError:
    file: ts-time/errors
    symbol: InvalidMonthError

includes:
  null: |
    <p class="text-secondary">Note that a method call on null or undefined always leads to an error.
    So, if your variable may contain null or undefined, use the respective static method instead.</p>

  weekBased: |
    <p class="text-secondary">By definition, the 1st week of week based year contains the 1st Thursday of the year, and
    the week based year starts from the Monday of this week.</p>

  experimental: |
    <p class="text-danger">This is an experimental API. There's a higher chance that the authors of the library may
    remove or change it in future releases.</p>

  DocumentationIndex: |
    <div class="container-fluid">
      <div class="row">
        <div class="col-6">
          <h5><a href="https://www.npmjs.com/package/ts-time" target="_blank">ts-time</a></h5>
          <ul class="list-unstyled">
            <li>%coreConstants</li>
            <li>%DayOfWeek</li>
            <li>%Duration</li>
            <li>%Era</li>
            <li>%errors</li>
            <li>%Instant</li>
            <li>%LocalDate</li>
            <li>%LocalDateTime</li>
            <li>%LocalTime</li>
            <li>%Month</li>
            <li>%OffsetDateTime</li>
            <li>%Period</li>
            <li>%TimeField</li>
            <li>%coreUtils</li>
            <li>%Zone</li>
            <li>%ZonedDateTime</li>
          </ul>
        </div>
        <div class="col-6">
          <h5><a href="https://www.npmjs.com/package/ts-time-format" target="_blank">ts-time-format</a></h5>
          <ul class="list-unstyled">
            <li>%formatConstants</li>
            <li>%DateFormatter</li>
            <li>%DateTimeFormatter</li>
            <li>%OffsetDateTimeFormatter</li>
            <li>%OffsetFormatter</li>
            <li>%TemporalCompiler</li>
            <li>%TemporalFormatter</li>
            <li>%TimeFormatter</li>
            <li>%formatUtils</li>
            <li>%ZonedDateTimeFormatter</li>
          </ul>
        </div>
      </div>
    </div>
